name: open_belvpn
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'
version: 1.0.5+9

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  loading_gifs: ^0.3.0
  flutter_spinkit: ^4.1.2
  dart_ipify: ^1.0.2
  percent_indicator: ^2.1.7+2
  bloc:
  flutter_bloc: ^7.0.1
  rxdart:
  firebase_core: "^1.4.0"
  cloud_firestore:
  firebase_storage:
  flutter_inapp_purchase:
  localstorage:
  firebase_remote_config: "^0.10.0+3"
  cached_network_image:
  intl:
  duration:
  country_codes: ^2.0.1
  device_info_plus:
  url_launcher:
  flutter_launcher_icons: ^0.9.1
  flutter_cache_manager: ^3.1.2
  flutter_markdown:

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_info: ^0.4.3


flutter:
  uses-material-design: true
  assets:
    - google_fonts/  
    - assets/svg_icons/
    - assets/images/
    - assets/vpn/
    - assets/icon/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon2.png"