name: open_belvpn
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  loading_gifs: ^0.3.0
  flutter_spinkit: ^4.1.2
  dart_ipify: ^1.0.2
  percent_indicator: ^2.1.7+2
  bloc:
  flutter_bloc: ^7.0.1
  rxdart:
  firebase_core:
  cloud_firestore:
  firebase_storage:
  flutter_inapp_purchase:
  localstorage:
  get_ip_address:
  dio:
  webview_flutter:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_info: ^0.4.3

flutter:
  uses-material-design: true
  assets:
    - google_fonts/  
    - assets/svg_icons/
    - assets/images/
    - assets/vpn/